sudo: required
language: node_js
node_js: 
    - "node"

services:
    - docker

install: npm install

script: npm run build

after_success:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p "$(cat keyfile.json)" us.gcr.io/brave-reason-142805;
    - export REPO=hocragekey/blog-ui
    - docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
    - docker images
    - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
    - docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO
    - docker tag blog-ui us.gcr.io/brave-reason-142805/blog
    - gcloud docker push us.gcr.io/brave-reason-142805/blog
    