sudo: required
language: node_js
node_js: 
    - "node"

services:
    - docker

install: npm install

script: npm run build

after_script:
    - export REPO="us.gcr.io/brave-reason-142805/blogui"
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p "$(cat keyfile.json)" $REPO;
    - export V="latest"
    - docker build -f Dockerfile -t $REPO:$V .
    - docker images
    - gcloud docker --authorize-only
    - docker push $REPO:$V
    