sudo: required
language: node_js
node_js: 
    - "node"

services:
    - docker

env:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - REPO="us.gcr.io/brave-reason-142805/blogui"
  - V="latest"
  
before_install:
  - curl https://sdk.cloud.google.com | bash
  - bash -l ./.gcloud version
  - bash -l ./.gcloud components update kubectl -q

install: npm install

script: 
    - npm run build

after_success:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p "$(cat keyfile.json)" $REPO;
    - docker build -f Dockerfile -t $REPO:$V .
    - docker images
    - gcloud docker --authorize-only
    - docker push $REPO:$V
    - export PATH=$PATH:/usr/local/share/google/google-cloud-sdk/bin/
    - ./gcloud kubectl run blog-ui1 --image=us.gcr.io/brave-reason-142805/blogui/ --port=8080
    - ./gcloud kubectl expose deployment blog-ui1 --type="LoadBalancer"