sudo: required
language: node_js
node_js: 
    - "node"

services:
    - docker

install: npm install

script: npm run build

after_script:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p "$(cat keyfile.json)" us.gcr.io/brave-reason-142805;
    - export REPO="hocragekey/blog-ui"
    - export V="latest"
    - docker build -f Dockerfile -t $REPO:$V .
    - docker images
    - docker tag $REPO:$V us.gcr.io/brave-reason-142805/blog-ui/$V
    - gcloud docker push us.gcr.io/brave-reason-142805/blog-ui/$V
    