sudo: required
language: node_js
node_js: 
    - "node"

services:
    - docker

install: npm install

script: npm run build

after_success:
    - docker build -t blog-ui .
    - docker images
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p "$(cat keyfile.json)" us.gcr.io/brave-reason-142805;
    - docker tag blog-ui us.gcr.io/brave-reason-142805/blog
    - gcloud docker push us.gcr.io/brave-reason-142805/blog
    